const CATCH_ERROR = 'ERROR OCCURED:\n\t';

const errors = {
    outOfListRange: `${CATCH_ERROR} Out of range!`,
    onlyOneElement: `${CATCH_ERROR} The only one element can't be removed!`,
};

